# NumPy Tutorial

Installation of NumPy
If you have Python and PIP already installed on a system, then installation of NumPy is very easy.

Install it using this command:
C:\Users\Your Name>pip install numpy

Import NumPy
Once NumPy is installed, import it in your applications by adding the import keyword:

import numpy

# NumPy as np

NumPy is usually imported under the np alias.

alias: In Python alias are an alternate name for referring to the same thing.

Create an alias with the as keyword while importing:

import numpy as np

# Dimensions in Arrays
A dimension in arrays is one level of array depth (nested arrays).

nested array: are arrays that have arrays as their elements.

# 1. 0-D Arrays
0-D arrays, or Scalars, are the elements in an array. Each value in an array is a 0-D array.

In [1]:
#Example:1
#Create a 0-D array with value 42

import numpy as np

arr = np.array(42)

print(arr)

42


# 2. 1-D Arrays
An array that has 0-D arrays as its elements is called uni-dimensional or 1-D array.

These are the most common and basic arrays.



In [2]:
#Example"2
#Create a 1-D array containing the values 1,2,3,4,5:

import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


# 3. 2-D Arrays
An array that has 1-D arrays as its elements is called a 2-D array.

These are often used to represent matrix or 2nd order tensors.

NumPy has a whole sub module dedicated towards matrix operations called numpy.mat



In [3]:
#Example:3
#Create a 2-D array containing two arrays with the values 1,2,3 and 4,5,6:

import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr)

[[1 2 3]
 [4 5 6]]


# 4. 3-D arrays
An array that has 2-D arrays (matrices) as its elements is called 3-D array.

These are often used to represent a 3rd order tensor.

In [4]:
#Example:4
#Create a 3-D array with two 2-D arrays, both containing two arrays with the values 1,2,3 and 4,5,6:

import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


# Check Number of Dimensions?
NumPy Arrays provides the ndim attribute that returns an integer that tells us how many dimensions the array have.

In [5]:
#Example:5
#Check how many dimensions the arrays have:

import numpy as np

a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


# Higher Dimensional Arrays
An array can have any number of dimensions.

When the array is created, you can define the number of dimensions by using the ndmin argument.

In [6]:
#Example:6
#Create an array with 5 dimensions and verify that it has 5 dimensions:

import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=7)

print(arr)
print('number of dimensions :', arr.ndim)


[[[[[[[1 2 3 4]]]]]]]
number of dimensions : 7


# Basic Array Operation Function

# 1. np.arange()

In [7]:
np.arange(11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
np.arange(0,11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
a=np.arange(0,11)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
a=np.arange(0,11)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10]


Note: when we use print statement to print the array in the varaible "a" we get this as an output.

In [11]:
a=np.arange(0,11,2)
a

array([ 0,  2,  4,  6,  8, 10])

In [12]:
a=np.arange(0,20,3)
a

array([ 0,  3,  6,  9, 12, 15, 18])

In [13]:
a=np.arange(0,21,3)
a

array([ 0,  3,  6,  9, 12, 15, 18])

In [14]:
a=np.arange(0,22,3)
a

array([ 0,  3,  6,  9, 12, 15, 18, 21])

In [15]:
a=np.arange(21,3)
a

array([], dtype=int32)

In [16]:
a=np.arange(0,0,3)
a

array([], dtype=int32)

Note: Basically this statement represent the array with the dtype: "array([], dtype=int32)"" 

# 2. np.ndim()

In [17]:
a=np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [18]:
np.ndim(a)

1

In [19]:
b=np.arange(12).reshape(3,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [20]:
np.ndim(b)

2

In [21]:
b=np.arange(12).reshape(3,4)
np.ndim(b)

2

Note:this "np.ndim" function denote the number of array it has.    

# 3. np.zeros()

In [22]:
np.zeros(3)

array([0., 0., 0.])

In [23]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

Note: 3 Denote number of rows, 4 denote number of column

In [24]:
np.arange(11).zeros(5)

AttributeError: 'numpy.ndarray' object has no attribute 'zeros'

Note:

# 4. np.ones()

In [25]:
np.ones(2)

array([1., 1.])

In [26]:
np.ones((3))

array([1., 1., 1.])

In [27]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

# 5. np.linspace()

In [28]:
np.linspace(0,5,5)

array([0.  , 1.25, 2.5 , 3.75, 5.  ])

In [29]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [30]:
np.linspace(0,5,50)

array([0.        , 0.10204082, 0.20408163, 0.30612245, 0.40816327,
       0.51020408, 0.6122449 , 0.71428571, 0.81632653, 0.91836735,
       1.02040816, 1.12244898, 1.2244898 , 1.32653061, 1.42857143,
       1.53061224, 1.63265306, 1.73469388, 1.83673469, 1.93877551,
       2.04081633, 2.14285714, 2.24489796, 2.34693878, 2.44897959,
       2.55102041, 2.65306122, 2.75510204, 2.85714286, 2.95918367,
       3.06122449, 3.16326531, 3.26530612, 3.36734694, 3.46938776,
       3.57142857, 3.67346939, 3.7755102 , 3.87755102, 3.97959184,
       4.08163265, 4.18367347, 4.28571429, 4.3877551 , 4.48979592,
       4.59183673, 4.69387755, 4.79591837, 4.89795918, 5.        ])

Note: linspace means that from 0 to 5, it should be divided equally till it reaches 50 points of numbers.

# 6. a.itemsize

In [31]:
a=np.arange(0,12)
a


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [32]:
a.itemsize

4

In [33]:
a=np.arange(100000,200000)
a.itemsize

4

Note: Round bracket is not used in the itemsize function

# 7. a.dtype

In [34]:
a=np.arange(0,12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [35]:
a.dtype

dtype('int32')

Note: dtype represent the type of data like integer, float, string. Note array doesnot have float & String value

In [36]:
a.dtype()

TypeError: 'numpy.dtype' object is not callable

Note: Round bracket is not used in dtype function

# 8. a.size

In [37]:
a=np.arange(0,12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [38]:
a.size

12

In [39]:
a=np.arange(0,12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [40]:
a.size

12

In [41]:
a=np.arange(100)
a.size

100

Note: Size represent the total numbers of elements in the array

# 9. a.shape

In [42]:
a=np.arange(0,12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [43]:
a.shape

(12,)

Note: This denote number of column

In [44]:
a=np.arange(0,12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [45]:
a.shape

(3, 4)

Note: Shape represent the information on dimension of Rows & Column

# 10. a.reshape

In [46]:
a=np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [47]:
a=np.arange(12).reshape(4,3)
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

Note: Reshape command generally reshape the dimension from (2,3) to (3,2)

# 11. a.ravel

In [48]:
a=np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [49]:
a.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

Note: Basically ravel command is used to flatten the array & most important it used round bracket

# 12. random number

In [50]:
ran=np.random.randint(100, size=15)
ran

array([27, 95, 57, 78, 47, 55, 72, 54, 47, 67, 32, 86,  7, 87, 88])

In [51]:
print(ran)

[27 95 57 78 47 55 72 54 47 67 32 86  7 87 88]


In [52]:
np.random.randint(5, size=(2, 4))

array([[2, 1, 4, 1],
       [4, 4, 2, 2]])

Note: Basically print the random number 

# 13. a.min() or np.min(a)

In [53]:
a=np.arange(12).reshape(3,4)
np.min(a)

0

In [54]:
b=np.arange(10,60).reshape(10,5)
b

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59]])

In [55]:
b.min()

10

In [56]:
np.min(b)

10

Note: Both the min() function show the correct value show we can use this.

In [57]:
a=np.random.randint(100, size=10)
a

array([11, 38, 92, 56, 81, 11, 74, 76, 69, 84])

In [58]:
a.min()

11

In [59]:
np.min(a)

11

# 14. a.max() or np.max(a)

In [60]:
a=np.random.randint(11,50, size=12)
a

array([27, 48, 12, 33, 35, 45, 40, 42, 48, 23, 29, 29])

In [61]:
a.max()

48

In [62]:
np.max(a)

48

# 15. np.sqrt()

In [63]:
np.sqrt(3)

1.7320508075688772

In [64]:
a=np.random.randint(11,50, size=12)
a

array([13, 21, 26, 31, 37, 24, 46, 19, 41, 44, 26, 22])

In [65]:
np.sqrt(a)

array([3.60555128, 4.58257569, 5.09901951, 5.56776436, 6.08276253,
       4.89897949, 6.78232998, 4.35889894, 6.40312424, 6.63324958,
       5.09901951, 4.69041576])

In [66]:
a=np.random.randint(11,50, size=12).reshape(3,4)
a

array([[13, 27, 36, 34],
       [48, 40, 17, 32],
       [30, 37, 15, 16]])

In [67]:
np.sqrt(a)

array([[3.60555128, 5.19615242, 6.        , 5.83095189],
       [6.92820323, 6.32455532, 4.12310563, 5.65685425],
       [5.47722558, 6.08276253, 3.87298335, 4.        ]])

# 16. np.Square()

In [68]:
a=np.random.randint(11,50, size=12).reshape(3,4)
a

array([[38, 26, 47, 49],
       [43, 13, 30, 33],
       [11, 12, 43, 23]])

In [69]:
np.square(a)

array([[1444,  676, 2209, 2401],
       [1849,  169,  900, 1089],
       [ 121,  144, 1849,  529]], dtype=int32)

# 17. np.std()

In [70]:
a=np.random.randint(11,50, size=12).reshape(3,4)
a

array([[41, 49, 12, 12],
       [24, 37, 25, 16],
       [29, 48, 47, 41]])

In [71]:
np.std(a)

13.336197609013848

In [72]:
a=np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [73]:
np.std(a)

3.452052529534663

# 18. array with dtype complex variable

In [74]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]], dtype=complex)
a

array([[1.+0.j, 2.+0.j, 3.+0.j],
       [4.+0.j, 5.+0.j, 6.+0.j],
       [7.+0.j, 8.+0.j, 9.+0.j]])

# 19. a.dot(b) or matrix product

In [75]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
a.dot(b)

array([[19, 22],
       [43, 50]])

In [76]:
b.dot(a)

array([[23, 34],
       [31, 46]])

# Basic Mathematical operation

In [77]:
a=np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [78]:
b=np.array([[7,8,9],[10,11,12]])
b

array([[ 7,  8,  9],
       [10, 11, 12]])

# 20. Sum

In [79]:
np.sum([0.5, 0.7, 0.2, 1.5], dtype=np.int32)

1

In [80]:
np.sum([0.5, 0.7, 0.2, 1.5], dtype=np.float32)

2.9

In [81]:
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[7,8,9],[10,11,12]])
a+b


array([[ 8, 10, 12],
       [14, 16, 18]])

In [82]:
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[7,8,9],[10,11,12]])
np.sum(a+b)

78

In [83]:
a=np.array([[1,2,3],[4,5,6]])
a
b=np.array([[7,8,9],[10,11,12]])
b
sum(a+b)

array([22, 26, 30])

# 21. Multiply

In [84]:
a*b

array([[ 7, 16, 27],
       [40, 55, 72]])

In [85]:
np.multiply(a,b)

array([[ 7, 16, 27],
       [40, 55, 72]])

# 22. Subtract

In [86]:
b-a

array([[6, 6, 6],
       [6, 6, 6]])

In [87]:
np.subtract(b,a)

array([[6, 6, 6],
       [6, 6, 6]])

# 23. Divide

In [88]:
b/a

array([[7. , 4. , 3. ],
       [2.5, 2.2, 2. ]])

In [89]:
np.divide(b,a)

array([[7. , 4. , 3. ],
       [2.5, 2.2, 2. ]])

# 24. Sum(axis=0)

In [90]:
a=np.array([[1,2],[4,5]])
a

array([[1, 2],
       [4, 5]])

In [91]:
b=np.array([[7,8],[10,11]])
b

array([[ 7,  8],
       [10, 11]])

In [92]:
a.sum(axis=0)

array([5, 7])

In [93]:
b.sum(axis=0)

array([17, 19])

In [94]:
b.sum(axis=0)

array([17, 19])

In [95]:
b.sum(axis=1)

array([15, 21])

In [96]:
a=np.array([[1,2],[4,5]])
b=np.array([[7,8],[10,11]])
a+b.sum(axis=0)

array([[18, 21],
       [21, 24]])

In [97]:
a+b.sum(axis=1)

array([[16, 23],
       [19, 26]])

# Here, the operation doesn't contunie 

In [98]:
c=np.array([[1,2,3],[4,5,6]])
c

array([[1, 2, 3],
       [4, 5, 6]])

In [99]:
c.sum(axis=0)

array([5, 7, 9])

In [100]:
d=np.array([[7,8,9],[10,11,12]])
d

array([[ 7,  8,  9],
       [10, 11, 12]])

In [101]:
e=np.array([[13,14,15],[16,17,18],[19,20,21]])
e

array([[13, 14, 15],
       [16, 17, 18],
       [19, 20, 21]])

In [102]:
d.sum(axis=0)

array([17, 19, 21])

In [103]:
c+d.sum(axis=0)

array([[18, 21, 24],
       [21, 24, 27]])

In [104]:
c+d.sum(axis=1)

ValueError: operands could not be broadcast together with shapes (2,3) (2,) 

In [105]:
c+e.sum(axis=1)

array([[43, 53, 63],
       [46, 56, 66]])

Note: 

# NumPy: Slicing, stacking array, Indexing & Boolean Arrays

# Topics:

1. Indexing & Slicing
2. Iterating through Arrays
3. Stacking together two Arrays
4. Indexing with Boolean Arrays

# 1. Indexing & Slicing

In [106]:
n=[6,7,8]
n

[6, 7, 8]

In [107]:
n[0:2]

[6, 7]

In [108]:
n[1:2]

[7]

In [109]:
n[1:3]

[7, 8]

In [110]:
n[-1]

8

Note: n[0:2], 0=include & 2=not Include

In [111]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [112]:
a[0:2,0:2]

array([[1, 2],
       [4, 5]])

In [113]:
a[0:2,2]

array([3, 6])

In [114]:
a[1,2]

6

In [115]:
a[-1]

array([7, 8, 9])

In [116]:
a[-1,-1]

9

In [117]:
a[-1,0:2]

array([7, 8])

In [118]:
a[:,1:3]

array([[2, 3],
       [5, 6],
       [8, 9]])

# 2. Iterating through arrays

In [119]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [120]:
for row in a:
    print(row)

[1 2 3]
[4 5 6]
[7 8 9]


In [121]:
for x in a:
  for y in x:
    print(y)

1
2
3
4
5
6
7
8
9


Note: Here row is also a kind of list you can print by continuing the slicing in the row

# 26. a.flat

In [122]:
for cell in a.flat:
    print(cell)

1
2
3
4
5
6
7
8
9


# 3. Stacking two arrays together

Stacking are two types
1. Vstack
2. Hstack

In [123]:
a=np.arange(6).reshape(3,2)
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [124]:
b=np.arange(6,12).reshape(3,2)
b

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

# 27. np.vstack((a,b))

In [125]:
np.vstack((a,b))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

# 28. hstack((a,b))

In [126]:
np.hstack((a,b))

array([[ 0,  1,  6,  7],
       [ 2,  3,  8,  9],
       [ 4,  5, 10, 11]])

# 29. stack((a,b))

In [127]:
np.stack((a,b))

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [128]:
np.stack((b,a))

array([[[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[ 0,  1],
        [ 2,  3],
        [ 4,  5]]])

# 30. np.hsplit

In [129]:
a=np.arange(30).reshape(2,15)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [130]:
np.hsplit(a,3)

[array([[ 0,  1,  2,  3,  4],
        [15, 16, 17, 18, 19]]), array([[ 5,  6,  7,  8,  9],
        [20, 21, 22, 23, 24]]), array([[10, 11, 12, 13, 14],
        [25, 26, 27, 28, 29]])]

In [131]:
np.hsplit(a,5)

[array([[ 0,  1,  2],
        [15, 16, 17]]), array([[ 3,  4,  5],
        [18, 19, 20]]), array([[ 6,  7,  8],
        [21, 22, 23]]), array([[ 9, 10, 11],
        [24, 25, 26]]), array([[12, 13, 14],
        [27, 28, 29]])]

In [132]:
result=np.hsplit(a,3)
result[0]

array([[ 0,  1,  2,  3,  4],
       [15, 16, 17, 18, 19]])

In [133]:
result=np.hsplit(a,3)
result[1]

array([[ 5,  6,  7,  8,  9],
       [20, 21, 22, 23, 24]])

In [134]:
result=np.hsplit(a,3)
result[2]

array([[10, 11, 12, 13, 14],
       [25, 26, 27, 28, 29]])

# 31. np.vsplit

In [135]:
a=np.arange(30).reshape(2,15)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [136]:
np.vsplit(a,2)

[array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]]),
 array([[15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])]

In [137]:
result=np.vsplit(a,2)
result[0]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]])

In [138]:
result=np.vsplit(a,2)
result[1]

array([[15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

# 4. Indexing with boolean arrays

In [139]:
a=np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [140]:
b=a>4
b

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [141]:
a[b]

array([ 5,  6,  7,  8,  9, 10, 11])

In [142]:
a[b]=-1
a

array([[ 0,  1,  2,  3],
       [ 4, -1, -1, -1],
       [-1, -1, -1, -1]])

# Iterate numpy array using nditer

In [143]:
a=np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [144]:
for row in a:
    print(row)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [145]:
for row in a:
    for b  in row:
        print(b)

0
1
2
3
4
5
6
7
8
9
10
11


# 32. a.flatten()

when we dont want to write two for loop we use "flatten" command to get the result in a single for loop.

In [146]:
a=np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [147]:
for cell in a.flatten():
    print(cell)

0
1
2
3
4
5
6
7
8
9
10
11


# 33. np.nditer of order="C"

In [148]:
a=np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [149]:
for x in np.nditer(a):
    print(x)

0
1
2
3
4
5
6
7
8
9
10
11


In [150]:
for x in np.nditer(a, order="C"):
    print(x)

0
1
2
3
4
5
6
7
8
9
10
11


Note: for order "C" must be in capital letter

# 34. np.nditer of order="F"

In [151]:
for x in np.nditer(a, order="F"):
    print(x)

0
4
8
1
5
9
2
6
10
3
7
11


Note: for order "F" must be in capital letter

# 35. External Loop 

for x in np.nditer (a,order="F", flag=['external_loop'])

In [152]:
a=np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [153]:
for x in np.nditer(a,order="F",flags=['external_loop']):
    print(x)

[0 4 8]
[1 5 9]
[ 2  6 10]
[ 3  7 11]


# 36. op_flags

In [154]:
a=np.arange(12).reshape(3,4)
for x in np.nditer(a,op_flags=['readwrite']):
    x[...]=x*x

In [155]:
a

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

# 37. Assign a new array

In [156]:
b=np.arange(3,15,4).reshape(3,1)
b

array([[ 3],
       [ 7],
       [11]])

# 38. Some technique for broadcasting array

In [157]:
for x,y in np.nditer([a,b]):
    print(x,y)

0 3
1 3
4 3
9 3
16 7
25 7
36 7
49 7
64 11
81 11
100 11
121 11


# Basic NumPy Operation

URL: https://numpy.org/doc/stable/user/quickstart.html